<a href="https://colab.research.google.com/github/muditkumar14/ml-project/blob/main/DATA_PREPROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)

Task 1 — Categorical Encoding

In [2]:
import sklearn
le=sklearn.preprocessing.LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df

   Gender     City    Size  Age  Fare
0       1   Mumbai   Small   25    15
1       0    Delhi   Large   45   300
2       0  Chennai  Medium   32    85
3       1   Mumbai   Large   60   450
4       0    Delhi   Small   28    20

In [3]:
df['Gender']

0    1
1    0
2    0
3    1
4    0
Name: Gender, dtype: int64

In [4]:
df=pd.get_dummies(df,columns=['City'])
df

   Gender    Size  Age  Fare  City_Chennai  City_Delhi  City_Mumbai
0       1   Small   25    15         False       False         True
1       0   Large   45   300         False        True        False
2       0  Medium   32    85          True       False        False
3       1   Large   60   450         False       False         True
4       0   Small   28    20         False        True        False

In [5]:
size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size'] = df['Size'].map(size_mapping)
df['Size']

0    0
1    2
2    1
3    2
4    0
Name: Size, dtype: int64

Task 2 — Feature Scaling

In [6]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

print(df)

   Gender  Size       Age      Fare  City_Chennai  City_Delhi  City_Mumbai
0       1     0 -0.411765 -0.250000         False       False         True
1       0     2  0.764706  0.767857         False        True        False
2       0     1  0.000000  0.000000          True       False        False
3       1     2  1.647059  1.303571         False       False         True
4       0     0 -0.235294 -0.232143         False        True        False